### ISSUE TITLE
initialisation of Configuration properties in constructor throws NPE

### ISSUE THREAD

**Issue by sanderginn** [vlingo/vlingo-symbio-jdbc#17]
In the latest commit (958d1ba) on Configuration, the base constructor is updated to add and initialise the new ConnectionProvider entity; furthermore, the functionality of `actualDatabaseName` was changed to use the database name as defined in the `connectionProvider` of the configuration. However, `actualDatabaseName` is called before `this.connectionProvider` is initialised, so any configuration throws a NPE (this applies to the [bootstrapping of the example project vlingo-eventjournal](https://github.com/vlingo/vlingo-examples/blob/master/vlingo-eventjournal/src/main/java/io/vlingo/eventjournal/Bootstrap.java) too).

A simple fix seems to be simply initialising `this.connectionProvider` before setting `this.actualDatabaseName`.

**Comment by VaughnVernon** [comment]
@sanderginn Thanks for reporting! Would you like to make that change?

**Comment by sanderginn** [comment]
@VaughnVernon OK - I'll submit a PR when I have some time.

**Comment by VaughnVernon** [comment]
@sanderginn Excellent, thanks! In case you think that won't be soon I can do it. I'd prefer to have this in our `0.9.0 RC1` (official first production release candidate) by Friday or Monday.

**Comment by VaughnVernon** [comment]
Fixed.
