### ISSUE TITLE
vlingo-symbio-jdbc stops the full build

### ISSUE THREAD

**Issue by anderskristian** [vlingo/vlingo-symbio-jdbc#28]
The build with running tests breaks 

An option could be to disable the tests as long as they do not run.

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] io.vlingo.symbio.store.journal.jdbc.postgres.PostgresJournalActorTest.testRedispatch(io.vlingo.symbio.store.journal.jdbc.postgres.PostgresJournalActorTest)
[ERROR]   Run 1: PostgresJournalActorTest>BasePostgresJournalTest.setUpDatabase:47->testConfiguration:18 » IllegalState
[ERROR]   Run 2: PostgresJournalActorTest>BasePostgresJournalTest.tearDownDatabase:58->BasePostgresJournalTest.dropDatabase:63 » NullPointer
[INFO] 

```

**Comment by VaughnVernon** [comment]
Hi @anderskristian At the moment the local platform build requires some special care. Please see the [README](Optional) for details.

**Comment by VaughnVernon** [comment]
@anderskristian ATM you must bounce the Postgres and MySQL databases between test runs.

```
$ ./pgbounce.sh
```

**Comment by anderskristian** [comment]
Hi @VaughnVernon 

Yes I have started the docker compose
But I have forgotten that I have the Elephant running local on my Mac. After stopping the elephant - it works again.
.. sorry for making the bug report
/Anders

PS: The elephant is /Applications/Postgres.app
