### ISSUE TITLE
JDBCJournalActor is missing a constructor (..and more)

### ISSUE THREAD

**Issue by Florian-Schoenherr** [vlingo/vlingo-symbio-jdbc#48]
### There is an assumption that Journals should have a constructor which just takes a dispatcher:
(this is used in schemata:) ![InMemoryJournalActor takes dispatcher](https://user-images.githubusercontent.com/65456722/96691846-ad0fbd00-1385-11eb-84f3-c0676f8c7cc2.png)
(this is inside the xoom-api:) 
![JDBCJournalActor takes dispatcher](https://user-images.githubusercontent.com/65456722/96692187-0bd53680-1386-11eb-9b67-bee19ffabeee.png)
Goes here, so dispatcher is in parameters:
![actorFor(final Class<T> protocol, final Class<? extends Actor> type, final Object...parameters)](https://user-images.githubusercontent.com/65456722/96695233-b6028d80-1389-11eb-9dad-116913ba103d.png)

The dispatcher ends up inside `Definition.parameters` and gets send to `ActorFactory.actorFor` and gets handled like this:
```
Actor actor = null;
//... some other checks, but with dispatcher it ends up here:
for (final Constructor<?> ctor : definition.type().getConstructors()) {
        if (ctor.getParameterCount() == definition.internalParameters().size()) {
          actor = start(ctor, definition, address, logger);
//...
if (actor == null) {
      throw new IllegalArgumentException("No constructor matches the given number of parameters.");
}
```
This would only work if every Journal built by `DefaultJournalActorBuilder` has a ctor with just one parameter like in:
```
public InMemoryJournalActor(final Dispatcher<Dispatchable<Entry<T>,RS>> dispatcher) {
    this.journal = new InMemoryJournal<>(dispatcher, stage().world());
}
```
..maybe even every `StoreActorBuilder` implementation needs this, then.
I don't know the specifics, maybe this needs to be build another way (change the `Definition`, so it's not just "`parameters`", which then just get used to look if the count of parameters is the same, but do it somehow else, more declarative).
Or if the Journals need this dispatcher ctor, maybe put something in the Journal interface.

I found this out because of related issue: https://github.com/vlingo/vlingo-xoom-starter/issues/3
They just use this, which doesn't seem wrong to me, please correct me if I'm wrong:
![simple startup code](https://user-images.githubusercontent.com/65456722/96694335-a3d41f80-1388-11eb-98ff-19df3c500749.png)

refs:
[ActorFactory](https://github.com/vlingo/vlingo-actors/blob/a72753abd7e04bfdf65cad0085737e15776acc99/src/main/java/io/vlingo/actors/ActorFactory.java#L77)
[InMemoryJournalActor](https://github.com/vlingo/vlingo-symbio/blob/7e819aa686db5ec27bbe993e1ccf47e327fb4606/src/main/java/io/vlingo/symbio/store/journal/inmemory/InMemoryJournalActor.java)
[JDBCJournalActor](https://github.com/vlingo/vlingo-symbio-jdbc/blob/0fcdfb9e32e91bcd43ca9f443df5f6ebf88764cf/src/main/java/io/vlingo/symbio/store/journal/jdbc/JDBCJournalActor.java)

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr I think that the original issue was not accurately written. There is not missing ctor. It's that the Starter's generated code for Event Sourcing used a non-existing ctor because the code generator is wrong. This is probably more due to Event Sourcing code gen being tested less than StateStore gen. If @danilo-ambrosio agrees this issue can be closed as a non-issue.

/cc @danilo-ambrosio

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon but this still wouldn't make sense. 
![dispatcher as ...parameters](https://user-images.githubusercontent.com/65456722/96753025-8fffdc00-13cf-11eb-82cd-04e348f58d25.png)
![parameters in Definition](https://user-images.githubusercontent.com/65456722/96753652-727f4200-13d0-11eb-88fa-62f14be639c7.png)
`dispatcher` ends up in `Definition.parameters`, so `ActorFactory` will never find any ctor. Or should there be an [`instantiator`](https://github.com/vlingo/vlingo-actors/blob/a72753abd7e04bfdf65cad0085737e15776acc99/src/main/java/io/vlingo/actors/ActorFactory.java#L70) inside `Definition` by then?

Maybe I just don't get it right now, so yes, if @danilo-ambrosio finds something or some version of this issue should be in xoom instead, this can be closed.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Please discuss and coordinate with @danilo-ambrosio. He told me that the fix could be done rather easily, but he didn't indicate how. I leave it to you two to work out.

**Comment by Florian-Schoenherr** [comment]
Fixed by https://github.com/vlingo/vlingo-xoom/commit/479d550cd3473dd015f347fae088765a91ad2adb.
